audit_header: false
title: Bay Area Real Estate Video Blog with Caleb Davis
description: Our mission at Fohl & Hhernandez Real Estate Brokerage is to be your best resource for Bay Area real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Fohl & Hhernandez Real Estate Brokerage, your professional Bay Area Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Caleb LL Davis
  title:
  license_number: 'CA BRE#: 01857920'
  about_markdown: |
    Caleb Davis, a Bay Area native maintains a pragmatic, service-driven approach with which he faces every real estate transaction. Caleb's passion for real estate started early, as he sold his first investment property at the age of 25. Having been personally mentored by Les Fohl since 2009, Caleb’s success can be attributed to his dedication to networking and marketing, his savvy negotiation skills, and ultimately, his relentless pursuit to be the exception and earn supreme client satisfaction. Caleb’s diverse experience allows him to provide unique insights and exceptional real estate client experiences. Caleb cherishes spending quality time with his wife & two daughters. When he’s not at home or at the office, Caleb can be found serving in the Army Reserves, as a regional director of a local charity or running on one of our beautiful Bay Area trails with His beloved huskies Kai & Koda.
  brand: Fohl & Hernandez Real Estate Brokerage
  brokerage:
  market: Bay Area
  address: 22326 Main Street, Hayward, CA 94542
  phone: 510-331-2654
  phone_type:
  phone2:
  phone2_type:
  email: Caleb@CalebLLDavis.com
  url: http://www.caleblldavis.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.caleblldavis.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.caleblldavis.com/map_search/results/5/1/#/?city=Hayward&type=res&page=1&per_page=20

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Bay Area Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.caleblldavis.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Bay Area Home?"
    CTA_text2: "Search the entire MLS for your Bay Area home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.caleblldavis.com/map_search/results/5/1/#/?city=Hayward&type=res&page=1&per_page=20

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/CalebLLDavis/
  linkedin_url: https://www.linkedin.com/in/caleb-ll-davis-1ba74613/
  youtube_url: https://www.youtube.com/channel/UCyHkYZAxuC-5j8ITMdMC3yw
  twitter_url: https://twitter.com/CalebLLDavis
  instagram_url:
  snapchat_url: https://www.snapchat.com/add/CalebLDavis
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Bay Area Real Estate Podcast with Caleb Davis'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Bay Area Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Fohl & Hhernandez Real Estate Brokerage - your professional Bay Area Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Bay Area, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Caleb Davis'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: Bay Area Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  theme_color: '#686868'
  brand_color: '#a60605'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
